### ISSUE TITLE
Fix for this module

### ISSUE THREAD

**Issue by Jargendas** [jannekalliola/MMM-BMWConnected#4]
Hi @jannekalliola,

I looked into the current state of the BMW APIs and discovered that BMW seems to have simply dropped the old BMW ConnectedDrive API in favor of the new MyBMW app. Even their own BMW ConnectedDrive app crashes, I still had it installed. This behaviour of just removing APIs without comment really annoys me on BMW's side...

However, while the MyBMW API is not public, people have reverse-engineered it for Home Assistant in the [bimmer_connected](https://github.com/bimmerconnected/bimmer_connected) project. Unfortunately, there is no node version though.

I have now forked and migrated this project to [MMM-MyBMW](https://github.com/Jargendas/MMM-MyBMW), which calls a python script using `bimmer_connected` in the background. At the moment, there is an issue downloading the vehicle image (which has worked before but broke now, maybe an API change), which I hope I can resolve in the next days, otherwise it works great.

If you don't care, you could archive this project, linking to the new one, or I can create a PR with my (substantial) changes if you want this repo to live on, whatever you prefer.

<img width="235" alt="Bildschirmfoto 2024-03-27 um 09 42 02" src="https://github.com/jannekalliola/MMM-BMWConnected/assets/1270412/b3ca4864-4e49-475d-9b7d-7d00f95690a4">

**Comment by jannekalliola** [comment]
Thank you for your work, I tested it today and found it working. I'll archive my project as obsolete and link to your project.
